version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "9999:80"
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app: &base
    image: ziwon/docker-rails
    build:
      context: .
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_BASE=topsecret1234567890
      - POSTMARK_API_KEY=i-am-not-your-api-key
      - SIDEKIQ_WEB_USERNAME=admin@local
      - SIDEKIQ_WEB_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  sidekiq:
    <<: *base
    ports:
      - "3001:3000"
    command: sidekiq

volumes:
  db_data:
